from typing import Union
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
app=FastAPI()

class Country(BaseModel):
    id:int
    code:Union[str,None]=str
    name:Union[str,None]=str
    continent:str
    region:str
    surface_area:Union[int,None]=int
    independence_year:Union[str,None]=str
    population:Union[int,None]=int
    life_expectancy:Union[float,None]=float
    gnp:Union[int,None]=int
    gnp_old:Union[float,None]=float
    local_name:Union[str,None]=str
    government_form:Union[str,None]=str
    head_of_state:Union[str,None]=str
    capital:Union[int,None]=int
    codetwo:Union[str,None]=str


CountryList=[
  Country(id= 1,code= "ABW",name= "Aruba",continent= "North America",region= "Caribbean",surface_area= 193,independence_year= 0,population= 103000,life_expectancy= 78.4,gnp= 828,gnp_old= 793,local_name= "Aruba",government_form= "Nonmetropolitan Territory of The Netherlands",head_of_state= "Willem-Alexander",capital= 129,codetwo= "AW"),
  Country(id= 2,code= "AFG",name= "Afghanistan",continent= "Asia",region= "Southern and Central Asia",surface_area= 652090,independence_year= 1919,population= 22720000,life_expectancy= 45.9,gnp= 5976,gnp_old= 0,local_name= "Afganistan/Afqanestan",government_form= "Islamic Emirate",head_of_state= "Mohammad Omar",capital= 1,codetwo= "AF"),
  Country(id= 3,code= "AGO",name= "Angola",continent= "Africa",region= "Central Africa",surface_area= 1246700,independence_year= 1975,population= 12878000,life_expectancy= 38.3,gnp= 6648,gnp_old= 7984,local_name= "Angola",government_form= "Republic",head_of_state= "Jose Eduardo dos Santos",capital= 56,codetwo= "AO"),
  Country(id= 4,code= "AIA",name= "Anguilla",continent= "North America",region= "Caribbean",surface_area= 96,independence_year= 0,population= 8000,life_expectancy= 76.1,gnp= 63.2,gnp_old= 0,local_name= "Anguilla",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 62,codetwo= "AI"),
  Country(id= 5,code= "ALB",name= "Albania",continent= "Europe",region= "Southern Europe",surface_area= 28748,independence_year= 1912,population= 3401200,life_expectancy= 71.6,gnp= 3205,gnp_old= 2500,local_name= "Shqiperia",government_form= "Republic",head_of_state= "Rexhep Mejdani",capital= 34,codetwo= "AL"),
  Country(id= 6,code= "AND",name= "Andorra",continent= "Europe",region= "Southern Europe",surface_area= 468,independence_year= 1278,population= 78000,life_expectancy= 83.5,gnp= 1630,gnp_old= 0,local_name= "Andorra",government_form= "Parliamentary Coprincipality",head_of_state= "",capital= 55,codetwo= "AD"),
  Country(id= 7,code= "ANT",name= "Netherlands Antilles",continent= "North America",region= "Caribbean",surface_area= 800,independence_year= 0,population= 217000,life_expectancy= 74.7,gnp= 1941,gnp_old= 0,local_name= "Nederlandse Antillen",government_form= "Nonmetropolitan Territory of The Netherlands",head_of_state= "Willem-Alexander",capital= 33,codetwo= "AN"),  
  Country(id= 8 ,code="ARE" ,name="united Arab Emirates" ,continent="Asia" ,region="Middle East" ,surface_area=83600 ,independence_year=1971,population=2441000 ,life_expectancy=74.1 ,gnp=37966 ,gnp_old=36846 ,local_name="Al-Imarat al- Arabiya al-Muttahida" ,government_form="Emirate Federation",head_of_state="Zayid bin Sultan al-Nahayan" ,capital=65 ,codetwo= "AE"),
  Country(id= 9,code= "ARG",name= "Argentina",continent= "South America",region= "South America",surface_area= 2780400,independence_year= 1816,population= 37032000,life_expectancy= 75.1,gnp= 340238,gnp_old= 323310,local_name= "Argentina",government_form= "Federal Republic",head_of_state= "Fernando de la Rua",capital= 69,codetwo= "AR"),
  Country(id= 10,code= "ARM",name= "Armenia",continent= "Asia",region= "Middle East",surface_area= 29800,independence_year= 1991,population= 3520000,life_expectancy= 66.4,gnp= 1813,gnp_old= 1627,local_name= "Hajastan",government_form= "Republic",head_of_state= "Robert KotSarjan",capital= 126,codetwo= "AM"),
  Country(id= 11,code= "ASM",name= "American Samoa",continent= "Oceania",region= "Polynesia",surface_area= 199,independence_year= 0,population= 68000,life_expectancy= 75.1,gnp= 334,gnp_old= 0,local_name= "Amerika Samoa",government_form= "uS Territory",head_of_state= "George W. Bush",capital= 54,codetwo= "AS"),
  Country(id= 12,code= "ATA",name= "Antarctica",continent= "Antarctica",region= "Antarctica",surface_area= 13120000,independence_year= 0,population= 0,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "N/A",government_form= "Co-administrated",head_of_state= "",capital= 0,codetwo= "AQ"),
  Country(id= 13,code= "ATF",name= "French Southern territories",continent= "Antarctica",region= "Antarctica",surface_area= 7780,independence_year= 0,population= 0,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Terres australes francaises",government_form= "Nonmetropolitan Territory of France",head_of_state= "Jacques Chirac",capital= 0,codetwo= "TF"),
  Country(id= 14,code= "ATG",name= "Antigua and Barbuda",continent= "North America",region= "Caribbean",surface_area= 442,independence_year= 1981,population= 68000,life_expectancy= 70.5,gnp= 612,gnp_old= 584,local_name= "Antigua and Barbuda",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 63,codetwo= "AG"),
  Country(id= 15,code= "AuS",name= "Australia",continent= "Oceania",region= "Australia and New Zealand",surface_area= 7741220,independence_year= 1901,population= 18886000,life_expectancy= 79.8,gnp= 351182,gnp_old= 392911,local_name= "Australia",government_form= "Constitutional Monarchy, Federation",head_of_state= "Elisabeth II",capital= 135,codetwo= "Au"),
  Country(id= 16,code= "AuT",name= "Austria",continent= "Europe",region= "Western Europe",surface_area= 83859,independence_year= 1918,population= 8091800,life_expectancy= 77.7,gnp= 211860,gnp_old= 206025,local_name= "osterreich",government_form= "Federal Republic",head_of_state= "Thomas Klestil",capital= 1523,codetwo= "AT"),
  Country(id= 17,code= "AZE",name= "Azerbaijan",continent= "Asia",region= "Middle East",surface_area= 86600,independence_year= 1991,population= 7734000,life_expectancy= 62.9,gnp= 4127,gnp_old= 4100,local_name= "Azarbaycan",government_form= "Federal Republic",head_of_state= "Heydar aliyev",capital= 144,codetwo= "AZ"),
  Country(id= 18,code= "BDI",name= "Burundi",continent= "Africa",region= "Eastern Africa",surface_area= 27834,independence_year= 1962,population= 6695000,life_expectancy= 46.2,gnp= 903,gnp_old= 982,local_name= "Burundi/uburundi",government_form= "Republic",head_of_state= "Pierre Buyoya",capital= 552,codetwo= "BI"),
  Country(id= 19,code= "BEL",name= "Belgium",continent= "Europe",region= "Western Europe",surface_area= 30518,independence_year= 1830,population= 10239000,life_expectancy= 77.8,gnp= 249704,gnp_old= 243948,local_name= "Belgie/Belgique",government_form= "Constitutional Monarchy, Federation",head_of_state= "Albert II",capital= 179,codetwo= "BE"),
  Country(id= 20,code= "BEN",name= "Benin",continent= "Africa",region= "Western Africa",surface_area= 112622,independence_year= 1960,population= 6097000,life_expectancy= 50.2,gnp= 2357,gnp_old= 2141,local_name= "Benin",government_form= "Republic",head_of_state= "Mathieu Kerekou",capital= 187,codetwo= "BJ"),
  Country(id= 21,code= "BFA",name= "Burkina Faso",continent= "Africa",region= "Western Africa",surface_area= 274000,independence_year= 1960,population= 11937000,life_expectancy= 46.7,gnp= 2425,gnp_old= 2201,local_name= "Burkina Faso",government_form= "Republic",head_of_state= "Blaise Compaore",capital= 549,codetwo= "BF"),
  Country(id= 22,code= "BGD",name="Bangladesh",continent= "Asia",region= "Southern and Central Asia",surface_area= 143998,independence_year= 1971,population= 129155000,life_expectancy= 60.2,gnp= 32852,gnp_old= 31966,local_name= "Bangladesh",government_form= "Republic",head_of_state= "Shahabuddin Ahmad",capital= 150,codetwo= "BD"),
  Country(id= 23,code= "BGR",name= "Bulgaria",continent= "Europe",region= "Eastern Europe",surface_area= 110994,independence_year= 1908,population= 8190900,life_expectancy= 70.9,gnp= 12178,gnp_old= 10169,local_name= "Balgarija",government_form= "Republic",head_of_state= "Petar Stojanov",capital= 539,codetwo= "BG"),
  Country(id= 24,code= "BHR",name= "Bahrain",continent= "Asia",region= "Middle East",surface_area= 694,independence_year= 1971,population= 617000,life_expectancy= 73,gnp= 6366,gnp_old= 6097,local_name= "Al-Bahrayn",government_form= "Monarchy (Emirate)",head_of_state= "Hamad ibn Isa al-Khalifa",capital= 149,codetwo= "BH"),
  Country(id= 25,code= "BHS",name= "Bahamas",continent= "North America",region= "Caribbean",surface_area= 13878,independence_year= 1973,population= 307000,life_expectancy= 71.1,gnp= 3527,gnp_old= 3347,local_name= "The Bahamas",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 148,codetwo= "BS"),
  Country(id= 26,code= "BIH",name= "Bosnia and Herzegovina",continent= "Europe",region= "Southern Europe",surface_area= 51197,independence_year= 1992,population= 3972000,life_expectancy= 71.5,gnp= 2841,gnp_old= 0,local_name= "Bosna i Hercegovina",government_form= "Federal Republic",head_of_state= "Ante Jelavic",capital= 201,codetwo= "BA"),
  Country(id= 27,code= "BLR",name= "Belarus",continent= "Europe",region= "Eastern Europe",surface_area= 207600,independence_year= 1991,population= 10236000,life_expectancy= 68,gnp= 13714,gnp_old= 0,local_name= "Belarus",government_form= "Republic",head_of_state= "Aljaksandr LukaSenka",capital= 3520,codetwo= "BY"),
  Country(id= 28,code= "BLZ",name= "Belize",continent= "North America",region= "Central America",surface_area= 22696,independence_year= 1981,population= 241000,life_expectancy= 70.9,gnp= 630,gnp_old= 616,local_name= "Belize",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 185,codetwo= "BZ"),
  Country(id= 29,code= "BMu",name= "Bermuda",continent= "North America",region= "North America",surface_area= 53,independence_year= 0,population= 65000,life_expectancy= 76.9,gnp= 2328,gnp_old= 2190,local_name= "Bermuda",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 191,codetwo= "BM"),
  Country(id= 30,code= "BOL",name= "Bolivia",continent= "South America",region= "South America",surface_area= 1098581,independence_year= 1825,population= 8329000,life_expectancy= 63.7,gnp= 8571,gnp_old= 7967,local_name= "Bolivia",government_form= "Republic",head_of_state= "Hugo Banzer Suarez",capital= 194,codetwo= "BO"),
  Country(id= 31,code= "BRA",name= "Brazil",continent= "South America",region= "South America",surface_area= 8547403,independence_year= 1822,population= 170115000,life_expectancy= 62.9,gnp= 776739,gnp_old= 804108,local_name= "Brasil",government_form= "Federal Republic",head_of_state= "Fernando Henrique Cardoso",capital= 211,codetwo= "BR"),
  Country(id= 32,code= "BRB",name= "Barbados",continent= "North America",region= "Caribbean",surface_area= 430,independence_year= 1966,population= 270000,life_expectancy= 73,gnp= 2223,gnp_old= 2186,local_name= "Barbados",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 174,codetwo= "BB"),
  Country(id= 33,code= "BRN",name= "Brunei",continent= "Asia",region= "Southeast Asia",surface_area= 5765,independence_year= 1984,population= 328000,life_expectancy= 73.6,gnp= 11705,gnp_old= 12460,local_name= "Brunei Darussalam",government_form= "Monarchy (Sultanate)",head_of_state= "Haji Hassan al-Bolkiah",capital= 538,codetwo= "BN"),
  Country(id= 34,code= "BTN",name= "Bhutan",continent= "Asia",region= "Southern and Central Asia",surface_area= 47000,independence_year= 1910,population= 2124000,life_expectancy= 52.4,gnp= 372,gnp_old= 383,local_name= "Druk-Yul",government_form= "Monarchy",head_of_state= "Jigme Singye Wangchuk",capital= 192,codetwo= "BT"),
  Country(id= 35,code= "BVT",name= "Bouvet Island",continent= "Antarctica",region= "Antarctica",surface_area= 59,independence_year= 0,population= 0,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Bouvetoya",government_form= "Dependent Territory of Norway",head_of_state= "Harald V",capital= 0,codetwo= "BV"),
  Country(id= 36,code= "BWA",name= "Botswana",continent= "Africa",region= "Southern Africa",surface_area= 581730,independence_year= 1966,population= 1622000,life_expectancy= 39.3,gnp= 4834,gnp_old= 4935,local_name= "Botswana",government_form= "Republic",head_of_state= "Festus G. Mogae",capital= 204,codetwo= "BW"),
  Country(id= 37,code= "CAF",name= "Central African Republic",continent= "Africa",region= "Central Africa",surface_area= 622984,independence_year= 1960,population= 3615000,life_expectancy= 44,gnp= 1054,gnp_old= 993,local_name= "Centrafrique/Be-Afrika",government_form= "Republic",head_of_state= "Ange-Felix Patasse",capital= 1889,codetwo= "CF"),
  Country(id= 38,code= "CAN",name= "Canada",continent= "North America",region= "North America",surface_area= 9970610,independence_year= 1867,population= 31147000,life_expectancy= 79.4,gnp= 598862,gnp_old= 625626,local_name= "Canada",government_form= "Constitutional Monarchy, Federation",head_of_state= "Elisabeth II",capital= 1822,codetwo= "CA"),
  Country(id= 39,code= "CCK",name= "Cocos (Keeling) Islands",continent= "Oceania",region= "Australia and New Zealand",surface_area= 14,independence_year= 0,population= 600,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Cocos (Keeling) Islands",government_form= "Territory of Australia",head_of_state= "Elisabeth II",capital= 2317,codetwo= "CC"),
  Country(id= 40,code= "CHE",name= "Switzerland",continent= "Europe",region= "Western Europe",surface_area= 41284,independence_year= 1499,population= 7160400,life_expectancy= 79.6,gnp= 264478,gnp_old= 256092,local_name= "Schweiz/Suisse/Svizzera/Svizra",government_form= "Federation",head_of_state= "Adolf Ogi",capital= 3248,codetwo= "CH"),
  Country(id= 41,code= "CHL",name= "Chile",continent= "South America",region= "South America",surface_area= 756626,independence_year= 1810,population= 15211000,life_expectancy= 75.7,gnp= 72949,gnp_old= 75780,local_name= "Chile",government_form= "Republic",head_of_state= "Ricardo Lagos Escobar",capital= 554,codetwo= "CL"),
  Country(id= 42,code= "CHN",name= "China",continent= "Asia",region= "Eastern Asia",surface_area= 9572900,independence_year= -1523,population= 1277558000,life_expectancy= 71.4,gnp= 982268,gnp_old= 917719,local_name= "Zhongquo",government_form= "People'sRepublic",head_of_state= "Jiang Zemin",capital= 1891,codetwo= "CN"),
  Country(id= 43,code= "CIV",name= "Cote dIvoire",continent= "Africa",region= "Western Africa",surface_area= 322463,independence_year= 1960,population= 14786000,life_expectancy= 45.2,gnp= 11345,gnp_old= 10285,local_name= "Cote dIvoire",government_form= "Republic",head_of_state= "Laurent Gbagbo",capital= 2814,codetwo= "CI"),
  Country(id= 44,code= "CMR",name= "Cameroon",continent= "Africa",region= "Central Africa",surface_area= 475442,independence_year= 1960,population= 15085000,life_expectancy= 54.8,gnp= 9174,gnp_old= 8596,local_name= "Cameroun/Cameroon",government_form= "Republic",head_of_state= "Paul Biya",capital= 1804,codetwo= "CM"),
  Country(id= 45,code= "COD",name= "Congo, The Democratic Republic of the",continent= "Africa",region= "Central Africa",surface_area= 2344858,independence_year= 1960,population= 51654000,life_expectancy= 48.8,gnp= 6964,gnp_old= 2474,local_name= "Republique Democratique du Congo",government_form= "Republic",head_of_state= "Joseph Kabila",capital= 2298,codetwo= "CD"),
  Country(id= 46,code= "COG",name= "Congo",continent= "Africa",region= "Central Africa",surface_area= 342000,independence_year= 1960,population= 2943000,life_expectancy= 47.4,gnp= 2108,gnp_old= 2287,local_name= "Congo",government_form= "Republic",head_of_state= "Denis Sassou-Nguesso",capital= 2296,codetwo= "CG"),
  Country(id= 47,code= "COK",name= "Cook Islands",continent= "Oceania",region= "Polynesia",surface_area= 236,independence_year= 0,population= 20000,life_expectancy= 71.1,gnp= 100,gnp_old= 0,local_name= "The Cook Islands",government_form= "Nonmetropolitan Territory of New Zealand",head_of_state= "Elisabeth II",capital= 583,codetwo= "CK"),
  Country(id= 48,code= "COL",name= "Colombia",continent= "South America",region= "South America",surface_area= 1138914,independence_year= 1810,population= 42321000,life_expectancy= 70.3,gnp= 102896,gnp_old= 105116,local_name= "Colombia",government_form= "Republic",head_of_state= "Andres Pastrana Arango",capital= 2257,codetwo= "CO"),
  Country(id= 49,code= "COM",name= "Comoros",continent= "Africa",region= "Eastern Africa",surface_area= 1862,independence_year= 1975,population= 578000,life_expectancy= 60,gnp= 4401,gnp_old= 4361,local_name= "Komori/Comores",government_form= "Republic",head_of_state= "Azali Assoumani",capital= 2295,codetwo= "KM"),
  Country(id= 50,code= "CPV",name= "Cape Verde",continent= "Africa",region= "Western Africa",surface_area= 4033,independence_year= 1975,population= 428000,life_expectancy= 68.9,gnp= 435,gnp_old= 420,local_name= "Cabo Verde",government_form= "Republic",head_of_state= "Antonio Mascarenhas Monteiro",capital= 1859,codetwo= "CV"),
  Country(id= 51,code= "CRI",name= "Costa Rica",continent= "North America",region= "Central America",surface_area= 51100,independence_year= 1821,population= 4023000,life_expectancy= 75.8,gnp= 10226,gnp_old= 9757,local_name= "Costa Rica",government_form= "Republic",head_of_state= "Miguel angel RodrIguez EcheverrIa",capital= 584,codetwo= "CR"),
  Country(id= 52,code= "CuB",name= "Cuba",continent= "North America",region= "Caribbean",surface_area= 110861,independence_year= 1902,population= 11201000,life_expectancy= 76.2,gnp= 17843,gnp_old= 18862,local_name= "Cuba",government_form= "Socialistic Republic",head_of_state= "Fidel Castro Ruz",capital= 2413,codetwo= "Cu"),
  Country(id= 53,code= "CXR",name= "Christmas Island",continent= "Oceania",region= "Australia and New Zealand",surface_area= 135,independence_year= 0,population= 2500,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Christmas Island",government_form= "Territory of Australia",head_of_state= "Elisabeth II",capital= 1791,codetwo= "CX"),
  Country(id= 54,code= "CYM",name= "Cayman Islands",continent= "North America",region= "Caribbean",surface_area= 264,independence_year= 0,population= 38000,life_expectancy= 78.9,gnp= 1263,gnp_old= 1186,local_name= "Cayman Islands",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 553,codetwo= "KY"),
  Country(id= 55,code= "CYP",name= "Cyprus",continent= "Asia",region= "Middle East",surface_area= 9251,independence_year= 1960,population= 754700,life_expectancy= 76.7,gnp= 9333,gnp_old= 8246,local_name= "Kypros/Kibris",government_form= "Republic",head_of_state= "Glafkos Klerides",capital= 2430,codetwo= "CY"),
  Country(id= 56,code= "CZE",name= "Czech Republic",continent= "Europe",region= "Eastern Europe",surface_area= 78866,independence_year= 1993,population= 10278100,life_expectancy= 74.5,gnp= 55017,gnp_old= 52037,local_name= "esko",government_form= "Republic",head_of_state= "Vaclav Havel",capital= 3339,codetwo= "CZ"),
  Country(id= 57,code= "DEu",name= "Germany",continent= "Europe",region= "Western Europe",surface_area= 357022,independence_year= 1955,population= 82164700,life_expectancy= 77.4,gnp= 2133367,gnp_old= 2102826,local_name= "Deutschland",government_form= "Federal Republic",head_of_state= "Johannes Rau",capital= 3068,codetwo= "DE"),
  Country(id= 58,code= "DJI",name= "Djibouti",continent= "Africa",region= "Eastern Africa",surface_area= 23200,independence_year= 1977,population= 638000,life_expectancy= 50.8,gnp= 382,gnp_old= 373,local_name= "Djibouti/Jibuti",government_form= "Republic",head_of_state= "Ismail Omar Guelleh",capital= 585,codetwo= "DJ"),
  Country(id= 59,code= "DMA",name= "Dominica",continent= "North America",region= "Caribbean",surface_area= 751,independence_year= 1978,population= 71000,life_expectancy= 73.4,gnp= 256,gnp_old= 243,local_name= "Dominica",government_form= "Republic",head_of_state= "Vernon Shaw",capital= 586,codetwo= "DM"),
  Country(id= 60,code= "DNK",name= "Denmark",continent= "Europe",region= "Nordic Countries",surface_area= 43094,independence_year= 800,population= 5330000,life_expectancy= 76.5,gnp= 174099,gnp_old= 169264,local_name= "Danmark",government_form= "Constitutional Monarchy",head_of_state= "Margrethe II",capital= 3315,codetwo= "DK"),
  Country(id= 61,code= "DOM",name= "Dominican Republic",continent= "North America",region= "Caribbean",surface_area= 48511,independence_year= 1844,population= 8495000,life_expectancy= 73.2,gnp= 15846,gnp_old= 15076,local_name= "Republica Dominicana",government_form= "Republic",head_of_state= "Hipolito MejIa DomInguez",capital= 587,codetwo= "DO"),
  Country(id= 62,code= "DZA",name= "Algeria",continent= "Africa",region= "Northern Africa",surface_area= 2381741,independence_year= 1962,population= 31471000,life_expectancy= 69.7,gnp= 49982,gnp_old= 46966,local_name= "Al-Jazair/Algerie",government_form= "Republic",head_of_state= "Abdelaziz Bouteflika",capital= 35,codetwo= "DZ"),
  Country(id= 63,code= "ECu",name= "Ecuador",continent= "South America",region= "South America",surface_area= 283561,independence_year= 1822,population= 12646000,life_expectancy= 71.1,gnp= 19770,gnp_old= 19769,local_name= "Ecuador",government_form= "Republic",head_of_state= "Gustavo Noboa Bejarano",capital= 594,codetwo= "EC"),
  Country(id= 64,code= "EGY",name= "Egypt",continent= "Africa",region= "Northern Africa",surface_area= 1001449,independence_year= 1922,population= 68470000,life_expectancy= 63.3,gnp= 82710,gnp_old= 75617,local_name= "Misr",government_form= "Republic",head_of_state= "Hosni Mubarak",capital= 608,codetwo= "EG"),
  Country(id= 65,code= "ERI",name= "Eritrea",continent= "Africa",region= "Eastern Africa",surface_area= 117600,independence_year= 1993,population= 3850000,life_expectancy= 55.8,gnp= 650,gnp_old= 755,local_name= "Ertra",government_form= "Republic",head_of_state= "Isayas Afewerki [Isaias Afwerki]",capital= 652,codetwo= "ER"),
  Country(id= 66,code= "ESH",name= "Western Sahara",continent= "Africa",region= "Northern Africa",surface_area= 266000,independence_year= 0,population= 293000,life_expectancy= 49.8,gnp= 60,gnp_old= 0,local_name= "As-Sahrawiya",government_form= "Occupied by Marocco",head_of_state= "Mohammed Abdel Aziz",capital= 2453,codetwo= "EH"),
  Country(id= 67,code= "ESP",name= "Spain",continent= "Europe",region= "Southern Europe",surface_area= 505992,independence_year= 1492,population= 39441700,life_expectancy= 78.8,gnp= 553233,gnp_old= 532031,local_name= "Espana",government_form= "Constitutional Monarchy",head_of_state= "Juan Carlos I",capital= 653,codetwo= "ES"),
  Country(id= 68,code= "EST",name= "Estonia",continent= "Europe",region= "Baltic Countries",surface_area= 45227,independence_year= 1991,population= 1439200,life_expectancy= 69.5,gnp= 5328,gnp_old= 3371,local_name= "Eesti",government_form= "Republic",head_of_state= "Lennart Meri",capital= 3791,codetwo= "EE"),
  Country(id= 69,code= "ETH",name= "Ethiopia",continent= "Africa",region= "Eastern Africa",surface_area= 1104300,independence_year= -1000,population= 62565000,life_expectancy= 45.2,gnp= 6353,gnp_old= 6180,local_name= "YeItyop iya",government_form= "Republic",head_of_state= "Negasso Gidada",capital= 756,codetwo= "ET"),
  Country(id= 70,code= "FIN",name= "Finland",continent= "Europe",region= "Nordic Countries",surface_area= 338145,independence_year= 1917,population= 5171300,life_expectancy= 77.4,gnp= 121914,gnp_old= 119833,local_name= "Suomi",government_form= "Republic",head_of_state= "Tarja Halonen",capital= 3236,codetwo= "FI"),
  Country(id= 71,code= "FJI",name= "Fiji Islands",continent= "Oceania",region= "Melanesia",surface_area= 18274,independence_year= 1970,population= 817000,life_expectancy= 67.9,gnp= 1536,gnp_old= 2149,local_name= "Fiji Islands",government_form= "Republic",head_of_state= "Josefa Iloilo",capital= 764,codetwo= "FJ"),
  Country(id= 72,code= "FLK",name= "Falkland Islands",continent= "South America",region= "South America",surface_area= 12173,independence_year= 0,population= 2000,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Falkland Islands",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 763,codetwo= "FK"),
  Country(id= 73,code= "FRA",name= "France",continent= "Europe",region= "Western Europe",surface_area= 551500,independence_year= 843,population= 59225700,life_expectancy= 78.8,gnp= 1424285,gnp_old= 1392448,local_name= "France",government_form= "Republic",head_of_state= "Jacques Chirac",capital= 2974,codetwo= "FR"),
  Country(id= 74,code= "FRO",name= "Faroe Islands",continent= "Europe",region= "Nordic Countries",surface_area= 1399,independence_year= 0,population= 43000,life_expectancy= 78.4,gnp= 0,gnp_old= 0,local_name= "Foroyar",government_form= "Part of Denmark",head_of_state= "Margrethe II",capital= 901,codetwo= "FO"),
  Country(id= 75,code= "FSM",name= "Micronesia, Federated States of",continent= "Oceania",region= "Micronesia",surface_area= 702,independence_year= 1990,population= 119000,life_expectancy= 68.6,gnp= 212,gnp_old= 0,local_name= "Micronesia",government_form= "Federal Republic",head_of_state= "Leo A. Falcam",capital= 2689,codetwo= "FM"),
  Country(id= 76,code= "GAB",name= "Gabon",continent= "Africa",region= "Central Africa",surface_area= 267668,independence_year= 1960,population= 1226000,life_expectancy= 50.1,gnp= 5493,gnp_old= 5279,local_name= "Le Gabon",government_form= "Republic",head_of_state= "Omar Bongo",capital= 902,codetwo= "GA"),
  Country(id= 77,code= "GBR",name= "united Kingdom",continent= "Europe",region= "British Islands",surface_area= 242900,independence_year= 1066,population= 59623400,life_expectancy= 77.7,gnp= 1378330,gnp_old= 1296830,local_name= "united Kingdom",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 456,codetwo= "GB"),
  Country(id= 78,code= "GEO",name= "Georgia",continent= "Asia",region= "Middle East",surface_area= 69700,independence_year= 1991,population= 4968000,life_expectancy= 64.5,gnp= 6064,gnp_old= 5924,local_name= "Sakartvelo",government_form= "Republic",head_of_state= "Eduard Sevardnadze",capital= 905,codetwo= "GE"),
  Country(id= 79,code= "GHA",name= "Ghana",continent= "Africa",region= "Western Africa",surface_area= 238533,independence_year= 1957,population= 20212000,life_expectancy= 57.4,gnp= 7137,gnp_old= 6884,local_name= "Ghana",government_form= "Republic",head_of_state= "John Kufuor",capital= 910,codetwo= "GH"),
  Country(id= 80,code= "GIB",name= "Gibraltar",continent= "Europe",region= "Southern Europe",surface_area= 6,independence_year= 0,population= 25000,life_expectancy= 79,gnp= 258,gnp_old= 0,local_name= "Gibraltar",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 915,codetwo= "GI"),
  Country(id= 81,code= "GIN",name= "Guinea",continent= "Africa",region= "Western Africa",surface_area= 245857,independence_year= 1958,population= 7430000,life_expectancy= 45.6,gnp= 2352,gnp_old= 2383,local_name= "Guinee",government_form= "Republic",head_of_state= "Lansana Conte",capital= 926,codetwo= "GN"),
  Country(id= 82,code= "GLP",name= "Guadeloupe",continent= "North America",region= "Caribbean",surface_area= 1705,independence_year= 0,population= 456000,life_expectancy= 77,gnp= 3501,gnp_old= 0,local_name= "Guadeloupe",government_form= "Overseas Department of France",head_of_state= "Jacques Chirac",capital= 919,codetwo= "GP"),
  Country(id= 83,code= "GMB",name= "Gambia",continent= "Africa",region= "Western Africa",surface_area= 11295,independence_year= 1965,population= 1305000,life_expectancy= 53.2,gnp= 320,gnp_old= 325,local_name= "The Gambia",government_form= "Republic",head_of_state= "Yahya Jammeh",capital= 904,codetwo= "GM"),
  Country(id= 84,code= "GNB",name= "Guinea-Bissau",continent= "Africa",region= "Western Africa",surface_area= 36125,independence_year= 1974,population= 1213000,life_expectancy= 49,gnp= 293,gnp_old= 272,local_name= "Guine-Bissau",government_form= "Republic",head_of_state= "Kumba Iala",capital= 927,codetwo= "GW"),
  Country(id= 85,code= "GNQ",name= "Equatorial Guinea",continent= "Africa",region= "Central Africa",surface_area= 28051,independence_year= 1968,population= 453000,life_expectancy= 53.6,gnp= 283,gnp_old= 542,local_name= "Guinea Ecuatorial",government_form= "Republic",head_of_state= "Teodoro Obiang Nguema Mbasogo",capital= 2972,codetwo= "GQ"),
  Country(id= 86,code= "GRC",name= "Greece",continent= "Europe",region= "Southern Europe",surface_area= 131626,independence_year= 1830,population= 10545700,life_expectancy= 78.4,gnp= 120724,gnp_old= 119946,local_name= "Ellada",government_form= "Republic",head_of_state= "Kostis Stefanopoulos",capital= 2401,codetwo= "GR"),
  Country(id= 87,code= "GRD",name= "Grenada",continent= "North America",region= "Caribbean",surface_area= 344,independence_year= 1974,population= 94000,life_expectancy= 64.5,gnp= 318,gnp_old= 0,local_name= "Grenada",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 916,codetwo= "GD"),
  Country(id= 88,code= "GRL",name= "Greenland",continent= "North America",region= "North America",surface_area= 2166090,independence_year= 0,population= 56000,life_expectancy= 68.1,gnp= 0,gnp_old= 0,local_name= "Kalaallit Nunaat/Gronland",government_form= "Part of Denmark",head_of_state= "Margrethe II",capital= 917,codetwo= "GL"),
  Country(id= 89,code= "GTM",name= "Guatemala",continent= "North America",region= "Central America",surface_area= 108889,independence_year= 1821,population= 11385000,life_expectancy= 66.2,gnp= 19008,gnp_old= 17797,local_name= "Guatemala",government_form= "Republic",head_of_state= "Alfonso Portillo Cabrera",capital= 922,codetwo= "GT"),
  Country(id= 90,code= "GuF",name= "French Guiana",continent= "South America",region= "South America",surface_area= 90000,independence_year= 0,population= 181000,life_expectancy= 76.1,gnp= 681,gnp_old= 0,local_name= "Guyane francaise",government_form= "Overseas Department of France",head_of_state= "Jacques Chirac",capital= 3014,codetwo= "GF"),
  Country(id= 91,code= "GuM",name= "Guam",continent= "Oceania",region= "Micronesia",surface_area= 549,independence_year= 0,population= 168000,life_expectancy= 77.8,gnp= 1197,gnp_old= 1136,local_name= "Guam",government_form= "uS Territory",head_of_state= "George W. Bush",capital= 921,codetwo= "Gu"),
  Country(id= 92,code= "GuY",name= "Guyana",continent= "South America",region= "South America",surface_area= 214969,independence_year= 1966,population= 861000,life_expectancy= 64,gnp= 722,gnp_old= 743,local_name= "Guyana",government_form= "Republic",head_of_state= "Bharrat Jagdeo",capital= 928,codetwo= "GY"),
  Country(id= 93,code= "HKG",name= "Hong Kong",continent= "Asia",region= "Eastern Asia",surface_area= 1075,independence_year= 0,population= 6782000,life_expectancy= 79.5,gnp= 166448,gnp_old= 173610,local_name= "Xianggang/Hong Kong",government_form= "Special Administrative Region of China",head_of_state= "Jiang Zemin",capital= 937,codetwo= "HK"),
  Country(id= 94,code= "HMD",name= "Heard Island and McDonald Islands",continent= "Antarctica",region= "Antarctica",surface_area= 359,independence_year= 0,population= 0,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "Heard and McDonald Islands",government_form= "Territory of Australia",head_of_state= "Elisabeth II",capital= 0,codetwo= "HM"),
  Country(id= 95,code= "HND",name= "Honduras",continent= "North America",region= "Central America",surface_area= 112088,independence_year= 1838,population= 6485000,life_expectancy= 69.9,gnp= 5333,gnp_old= 4697,local_name= "Honduras",government_form= "Republic",head_of_state= "Carlos Roberto Flores Facusse",capital= 933,codetwo= "HN"),
  Country(id= 96,code= "HRV",name= "Croatia",continent= "Europe",region= "Southern Europe",surface_area= 56538,independence_year= 1991,population= 4473000,life_expectancy= 73.7,gnp= 20208,gnp_old= 19300,local_name= "Hrvatska",government_form= "Republic",head_of_state= "Stipe Mesic",capital= 2409,codetwo= "HR"),
  Country(id= 97,code= "HTI",name= "Haiti",continent= "North America",region= "Caribbean",surface_area= 27750,independence_year= 1804,population= 8222000,life_expectancy= 49.2,gnp= 3459,gnp_old= 3107,local_name= "Haiti/Dayti",government_form= "Republic",head_of_state= "Jean-Bertrand Aristide",capital= 929,codetwo= "HT"),
  Country(id= 98,code= "HuN",name= "Hungary",continent= "Europe",region= "Eastern Europe",surface_area= 93030,independence_year= 1918,population= 10043200,life_expectancy= 71.4,gnp= 48267,gnp_old= 45914,local_name= "Magyarorszag",government_form= "Republic",head_of_state= "Ferenc Madl",capital= 3483,codetwo= "Hu"),
  Country(id= 99,code= "IDN",name= "Indonesia",continent= "Asia",region= "Southeast Asia",surface_area= 1904569,independence_year= 1945,population= 212107000,life_expectancy= 68,gnp= 84982,gnp_old= 215002,local_name= "Indonesia",government_form= "Republic",head_of_state= "Abdurrahman Wahid",capital= 939,codetwo= "ID"),
  Country(id= 100,code= "IND",name= "India",continent= "Asia",region= "Southern and Central Asia",surface_area= 3287263,independence_year= 1947,population= 1013662000,life_expectancy= 62.5,gnp= 447114,gnp_old= 430572,local_name= "Bharat/India",government_form= "Federal Republic",head_of_state= "Kocheril Raman Narayanan",capital= 1109,codetwo= "IN"),
  Country(id= 101,code= "IOT",name= "British Indian Ocean Territory",continent= "Africa",region= "Eastern Africa",surface_area= 78,independence_year= 0,population= 0,life_expectancy= 0,gnp= 0,gnp_old= 0,local_name= "British Indian Ocean Territory",government_form= "Dependent Territory of the uK",head_of_state= "Elisabeth II",capital= 0,codetwo= "IO"),
  Country(id= 102,code= "IRL",name= "Ireland",continent= "Europe",region= "British Islands",surface_area= 70273,independence_year= 1921,population= 3775100,life_expectancy= 76.8,gnp= 75921,gnp_old= 73132,local_name= "Ireland/eire",government_form= "Republic",head_of_state= "Mary McAleese",capital= 1447,codetwo= "IE"),
  Country(id= 103,code= "IRN",name= "Iran",continent= "Asia",region= "Southern and Central Asia",surface_area= 1648195,independence_year= 1906,population= 67702000,life_expectancy= 69.7,gnp= 195746,gnp_old= 160151,local_name= "Iran",government_form= "Islamic Republic",head_of_state= "Ali Mohammad Khatami-Ardakani",capital= 1380,codetwo= "IR"),
  Country(id= 104,code= "IRQ",name= "Iraq",continent= "Asia",region= "Middle East",surface_area= 438317,independence_year= 1932,population= 23115000,life_expectancy= 66.5,gnp= 11500,gnp_old= 0,local_name= "Al- Iraq",government_form= "Republic",head_of_state= "Saddam Hussein al-Takriti",capital= 1365,codetwo= "IQ"),
  Country(id= 105,code= "ISL",name= "Iceland",continent= "Europe",region= "Nordic Countries",surface_area= 103000,independence_year= 1944,population= 279000,life_expectancy= 79.4,gnp= 8255,gnp_old= 7474,local_name= "Island",government_form= "Republic",head_of_state= "olafur Ragnar GrImsson",capital= 1449,codetwo= "IS"),
  Country(id= 106,code= "ISR",name= "Israel",continent= "Asia",region= "Middle East",surface_area= 21056,independence_year= 1948,population= 6217000,life_expectancy= 78.6,gnp= 97477,gnp_old= 98577,local_name= "Yisrael/Israil",government_form= "Republic",head_of_state= "Moshe Katzav",capital= 1450,codetwo= "IL"),
  Country(id= 107,code= "ITA",name= "Italy",continent= "Europe",region= "Southern Europe",surface_area= 301316,independence_year= 1861,population= 57680000,life_expectancy= 79,gnp= 1161755,gnp_old= 1145372,local_name= "Italia",government_form= "Republic",head_of_state= "Carlo Azeglio Ciampi",capital= 1464,codetwo= "IT"),
  Country(id= 108,code= "JAM",name= "Jamaica",continent= "North America",region= "Caribbean",surface_area= 10990,independence_year= 1962,population= 2583000,life_expectancy= 75.2,gnp= 6871,gnp_old= 6722,local_name= "Jamaica",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 1530,codetwo= "JM"),
  Country(id= 109,code= "JOR",name= "Jordan",continent= "Asia",region= "Middle East",surface_area= 88946,independence_year= 1946,population= 5083000,life_expectancy= 77.4,gnp= 7526,gnp_old= 7051,local_name= "Al-urdunn",government_form= "Constitutional Monarchy",head_of_state= "Abdullah II",capital= 1786,codetwo= "JO"),
  Country(id= 110,code= "JPN",name= "Japan",continent= "Asia",region= "Eastern Asia",surface_area= 377829,independence_year= -660,population= 126714000,life_expectancy= 80.7,gnp= 3787042,gnp_old= 4192638,local_name= "Nihon/Nippon",government_form= "Constitutional Monarchy",head_of_state= "Akihito",capital= 1532,codetwo= "JP"),
  Country(id= 111,code= "KAZ",name= "Kazakstan",continent= "Asia",region= "Southern and Central Asia",surface_area= 2724900,independence_year= 1991,population= 16223000,life_expectancy= 63.2,gnp= 24375,gnp_old= 23383,local_name= "Qazaqstan",government_form= "Republic",head_of_state= "Nursultan Nazarbajev",capital= 1864,codetwo= "KZ"),
  Country(id= 112,code= "KEN",name= "Kenya",continent= "Africa",region= "Eastern Africa",surface_area= 580367,independence_year= 1963,population= 30080000,life_expectancy= 48,gnp= 9217,gnp_old= 10241,local_name= "Kenya",government_form= "Republic",head_of_state= "Daniel arap Moi",capital= 1881,codetwo= "KE"),
  Country(id= 113,code= "KGZ",name= "Kyrgyzstan",continent= "Asia",region= "Southern and Central Asia",surface_area= 199900,independence_year= 1991,population= 4699000,life_expectancy= 63.4,gnp= 1626,gnp_old= 1767,local_name= "Kyrgyzstan",government_form= "Republic",head_of_state= "Askar Akajev",capital= 2253,codetwo= "KG"),
  Country(id= 114,code= "KHM",name= "Cambodia",continent= "Asia",region= "Southeast Asia",surface_area= 181035,independence_year= 1953,population= 11168000,life_expectancy= 56.5,gnp= 5121,gnp_old= 5670,local_name= "Kampuchea",government_form= "Constitutional Monarchy",head_of_state= "Norodom Sihanouk",capital= 1800,codetwo= "KH"),
  Country(id= 115,code= "KIR",name= "Kiribati",continent= "Oceania",region= "Micronesia",surface_area= 726,independence_year= 1979,population= 83000,life_expectancy= 59.8,gnp= 40.7,gnp_old= 0,local_name= "Kiribati",government_form= "Republic",head_of_state= "Teburoro Tito",capital= 2256,codetwo= "KI"),
  Country(id= 116,code= "KNA",name= "Saint Kitts and Nevis",continent= "North America",region= "Caribbean",surface_area= 261,independence_year= 1983,population= 38000,life_expectancy= 70.7,gnp= 299,gnp_old= 0,local_name= "Saint Kitts and Nevis",government_form= "Constitutional Monarchy",head_of_state= "Elisabeth II",capital= 3064,codetwo= "KN"),
  Country(id= 117,code= "KOR",name= "South Korea",continent= "Asia",region= "Eastern Asia",surface_area= 99434,independence_year= 1948,population= 46844000,life_expectancy= 74.4,gnp= 320749,gnp_old= 442544,local_name= "Taehan Minguk (Namhan)",government_form= "Republic",head_of_state= "Kim Dae-jung",capital= 2331,codetwo= "KR"),
  Country(id= 118,code= "KWT",name= "Kuwait",continent= "Asia",region= "Middle East",surface_area= 17818,independence_year= 1961,population= 1972000,life_expectancy= 76.1,gnp= 27037,gnp_old= 30373,local_name= "Al-Kuwayt",government_form= "Constitutional Monarchy (Emirate)",head_of_state= "Jabir al-Ahmad al-Jabir al-Sabah",capital= 2429,codetwo= "KW"),
  Country(id= 119,code= "LAO",name= "Laos",continent= "Asia",region= "Southeast Asia",surface_area= 236800,independence_year= 1953,population= 5433000,life_expectancy= 53.1,gnp= 1292,gnp_old= 1746,local_name= "Lao",government_form= "Republic",head_of_state= "Khamtay Siphandone",capital= 2432,codetwo= "LA"),
  Country(id= 120,code= "LBN",name= "Lebanon",continent= "Asia",region= "Middle East",surface_area= 10400,independence_year= 1941,population= 3282000,life_expectancy= 71.3,gnp= 17121,gnp_old= 15129,local_name= "Lubnan",government_form= "Republic",head_of_state= "emile Lahoud",capital= 2438,codetwo= "LB")
]

@app.get("/continents/region/",status_code=200)
async def continents():
    return (CountryList)

@app.get("/continents/region/{id}",status_code=200) #Read
async def continents(id:int):
    continents=filter(lambda continent:continent.id == id, CountryList)
    try:
        return list(continents)[0]
    except:
        raise HTTPException(status_code=404,detail="No se ha encontrado la informacion")

@app.post("/continents/region/",status_code=201) #Create
async def continents(continent:Country):

    for index, guardar in enumerate(CountryList):
        if guardar.id == continent.id:
            raise HTTPException(status_code=404,detail="Los datos ya existe")
    else:
        CountryList.append(continent)
        return {
            "id=": continent.id,
            "continent=" : continent.continent,
            "region" : continent.region
        }


@app.put("/continents/region/",status_code=204) #Update
async def continents(continent:Country):
    
    found=False      
    
    for index, saved in enumerate(CountryList):
        if saved.id == continent.id:
           CountryList[index] = continent  
           found=True
           
    if not found:
        raise HTTPException(status_code=404,detail="No se ha actualizado los datos")
    else:
        return continent

@app.delete("/continents/region/{id}",status_code=204) #Delete
async def continents(id:int):
    
    found=False      
    
    for index, saved in enumerate(CountryList):
        if saved.id ==id:  
           del CountryList[index] 
           found=True
           return "El registro se ha eliminado"
       
    if not found:
        raise HTTPException(status_code=404,detail="No se ha eliminado el usuario")